#!/usr/bin/env python

# a program to collect lists of all songs played by a pandora station
# create a directory if there is not one
# create a station file if there is not one
# list station songs to one file per station

# requires pianobar

# Jared Henry Oviatt

import os
import subprocess
import sys
import argparse

songs_path = ""

station = "none"
song = "none"

def check_dir():
  if os.path.exists(songs_path):
    return
  else:
    subprocess.call('mkdir', songs_path)
    return

def new_file():
  global station
  print('Creating file for station ' + station)
  f = open(songs_path + station, 'w')
  f.write('This is a list of all songs played on Pandora station ' + station.replace('_',' ') + '\n')
  f.close()
  return

def check_file():
  global station
  if os.path.exists(songs_path + station):
    return 0
  else:
    new_file()
    return

def add_song():
  global song
  if check_songs():
    return
  print('Adding ' + song + ' to file ' + station)
  f = open(songs_path + station, 'a')
  f.write(song+'\n')
  f.close()
  return

def check_songs():
  global song
  f = open(songs_path + station, 'r')
  if song in f.read():
    print('This song is on the list')
    return 1
  return 0
  

def parse_output(filename):
  f = open(filename, 'r')
  raw = f.readlines()
  f.close
  
  cooked = []
  global station
  global song

  for line in raw:
    if '|>' not in line:
      continue
    else:
      cooked.append(line)

  for line in cooked:
    if 'Station' in line[:20]:
      lstation = line.split('>')
      station = lstation[1]
      lsplit = station.split('"')
      station = lsplit[1]
      station = station.replace(' ','_')
      print(station)
      check_file()
    else:
      lsong = line.split('>')
      song = lsong[1][:-2]
      add_song()

  return

def start_pianobar():
  pb = subprocess.Popen(['pianobar', '>>',  songs_path + 'raw.txt'], -1)
  # login
  pb.communicate()
  return

def parse_config():
  lconfig = []

  f = open(os.path.expanduser('~/.pianobook'), 'r')
  lines = f.readlines()

  for line in lines:
    if '#' in line or '\n' is line:
      continue
    else:
      lconfig.append(line)
  
  if len(lconfig) != 1:
    print("Check your ~/.pianobar config file")

  path = lconfig[0][5:].strip()
  
  return path

def main():

  global songs_path

# parse config file
  list_path = parse_config()

  songs_path = list_path + 'pandora_song_lists/'

# check args (-h) help (-o) parse only (-f) filename
  parser = argparse.ArgumentParser(description='Complete, organized song history for Pandora (via pianobar) - Config file is ~/.pianobar - update before using pianobook')
  parser.add_argument('-o', '--parse_only', action='count', help='Parse an existing file')
  parser.add_argument('-f', '--filename', default=songs_path+'raw.txt', metavar='FILE', type=str, help='Alternate file to be used instead of pandora_song_lists/raw.txt')
  args = parser.parse_args()
  if args.parse_only:
    print(" Parse Only mode on file " + args.filename)
    parse_output(args.filename)
    return

# check directory structure
  check_dir()

### Working on fixing this...
# start pianobar
  print('Starting pianobar...')
  start_pianobar()

# parse output file 
  print('Parsing file...')
  parse_output(args.filename)

  return

if __name__ == '__main__':
  main()
