#!/usr/bin/env python

# a script to collect lists of all songs played by a pandora station
# use bs4
# create a directory if there is not one
# create a station file if there is not one
# list station songs to one file per station

# requires pianobar

# Jared Henry Oviatt

import os
import sys
import argparse

LIST_DIR_PATH = "/home/jho/code/py/pan_list/"
songs_path = LIST_DIR_PATH + 'pandora_song_lists/'

station = "none"
song = "none"

def check_dir():
  if os.path.exists(songs_path):
    return
  else:
    os.system('mkdir ' + songs_path)
    return

def new_file():
  global station
  print('Creating file for station ' + station)
  f = open(songs_path + station, 'w')
  f.write('This is a list of all songs played on Pandora station ' + station.replace('_',' ') + '\n')
  f.close()
  return

def check_file():
  global station
  if os.path.exists(songs_path + station):
    return 0
  else:
    new_file()
    return

def add_song():
  global song
  if check_songs():
    return
  print('Adding ' + song + ' to file ' + station)
  f = open(songs_path + station, 'a')
  f.write(song+'\n')
  f.close()
  return

def check_songs():
  global song
  f = open(songs_path + station, 'r')
  if song in f.read():
    print('This song is on the list')
    return 1
  return 0
  

def parse_output(filename):
  f = open(filename, 'r')
  raw = f.readlines()
  f.close
  
 # os.remove(filename)
  
  cooked = []
  global station
  global song

  for line in raw:
    if '|>' not in line:
      continue
    else:
      cooked.append(line)

  print(cooked)

  for line in cooked:
    if 'Station' in line[:20]:
      lstation = line.split('>')
      station = lstation[1]
      lsplit = station.split('"')
      station = lsplit[1]
      station = station.replace(' ','_')
      print(station)
      check_file()
    else:
      lsong = line.split('>')
      song = lsong[1][:-2]
      add_song()

  return

def pianobar(email, password):
  start_pianobar(email, password)
  choose_station()
 
  close = input('\npress ENTER to quit\n')
  SOMETHING.write('q\n')

def start_pianobar(email, password):
  os.system('pianobar >> ' +  songs_path + 'raw.txt')
  # login
  SOMETHING.write(email)
  SOMETHING.write(password)
  return

def choose_station():
  songs_path = LIST_DIR_PATH + 'pandora_song_lists/'
  os.system('cat ' + songs_path + 'raw.txt')
  return

def quit_pianobar():
  SOMETHING.write('q')
  return

def main():
# check args (-h) help (-e) email (-p) passwd (-o) parse only
  parser = argparse.ArgumentParser(description='Complete, organized song history for pianobar/Pandora')
  parser.add_argument('-e', '--email', default='none', nargs='?', metavar='EMAIL', type=str, help='Pandora Username')
  parser.add_argument('-p', '--passwd', default='none', nargs='?', metavar='PASS', type=str, help='Pandora Password')
  parser.add_argument('-o', '--parse_only', action='count', help='Parse an existing file')
  parser.add_argument('-f', '--filename', default=songs_path+'raw.txt', metavar='FILE', type=str, help='Alternate file to be used instead of pandora_song_lists/raw.txt')
  args = parser.parse_args()
  if args.parse_only:
    print(" Parse Only mode on file " + args.filename)
    parse_output(args.filename)
    return

# check directory structure
  check_dir()

### Working on fixing this...
# start pianobar
#  print('Starting pianobar...')
#  pianobar(email, passwd)

# parse output file 
  print('Parsing file...')
  parse_output(args.filename)

  return

if __name__ == '__main__':
  main()
